import "./globals.css";

import LockScreen from "@/components/LockScreen";
import { MazzardRegular } from "@/utils/fonts";
import type { Metadata } from "next";
import { ModalProvider } from "@/utils/ModalContext";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${MazzardRegular.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider>
            <LockScreen />
            {/* <Nav /> */}
            {children}
          </ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
